platform :ios, '10.0'

target 'Beacon' do
  pod 'SDWebImage', '~>3.8'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'AFNetworking', '~> 3.0'
  pod 'YYCache'
  pod "DKNightVersion"

  target 'BeaconTests' do
  end

end
